apiVersion: apps/v1
kind: Deployment
metadata:
  name: K8S_POD_NAME
  namespace: K8S_NS
  labels:
    app: K8S_POD_NAME
spec:
  replicas: 1
  revisionHistoryLimit: 15
  selector:
    matchLabels:
      app: K8S_POD_NAME
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: K8S_POD_NAME
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - K8S_POD_NAME
                topologyKey: kubernetes.io/hostname
              weight: 100
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: K8S_POD_NAME
          image: DOCKER_CONTAINER_IMAGE_URL
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: K8S_POD_NAME
  namespace: K8S_NS
  labels:
    app: K8S_POD_NAME
spec:
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
  selector:
    app: K8S_POD_NAME
